image:
  repository: tccr.io/truecharts/habridge
  pullPolicy: IfNotPresent
  tag: v5.4.1@sha256:5d8d11eb44192405b240037dd1fbeec753ebaa38dba959849d1ad6a918e28e59

securityContext:
  runAsNonRoot: false
  readOnlyRootFilesystem: false

podSecurityContext:
  runAsUser: 0
  runAsGroup: 0

secretEnv:
  SEC_KEY: ""

service:
  main:
    ports:
      main:
        targetPort: 8080
        port: 10146
  comm:
    enabled: true
    ports:
      comm:
        enabled: true
        targetPort: 50000
        port: 50000

persistence:
  config:
    enabled: true
    mountPath: "/config"
  varrun:
    enabled: true

portal:
  enabled: true
