image:
  repository: tccr.io/truecharts/wireshark
  pullPolicy: IfNotPresent
  tag: v4.0.1@sha256:b92c0dc90036dff0860165a7a9021a17fd4f5f982f70c616382241183eb05af3

securityContext:
  readOnlyRootFilesystem: false
  runAsNonRoot: false
  capabilities:
    add:
      - NET_ADMIN

podSecurityContext:
  runAsUser: 0
  runAsGroup: 0

hostNetwork: true

service:
  main:
    ports:
      main:
        targetPort: 3000
        protocol: HTTP
        port: 3000

probes:
  liveness:
    path: /
  readiness:
    path: /
  startup:
    path: /

persistence:
  varrun:
    enabled: true
  config:
    enabled: true
    mountPath: /config

portal:
  enabled: true
