image:
  repository: tccr.io/truecharts/libreoffice
  pullPolicy: IfNotPresent
  tag: v7.3.7@sha256:58c023e85da6576424b3bb4f5b12bf3bbdd3a19840afd27fa3cd805973eaab5f

securityContext:
  runAsNonRoot: false
  readOnlyRootFilesystem: false

podSecurityContext:
  runAsUser: 0
  runAsGroup: 0

service:
  main:
    ports:
      main:
        targetPort: 3000
        port: 10133

persistence:
  config:
    enabled: true
    mountPath: "/config"
  varrun:
    enabled: true

portal:
  enabled: true
